import tkinter as tk

def create_settings_frame(window, widthIn, heightIn):
    global tokens_entry #global variables can be accessed from anywhere within the script and can even be access in any module that imports a module with a global variable contained within it. thus theoretically, a complete pants on head retard could have a single file that has every variable listed as a global variable and then has that module be imported so that the program can store data. a really bad idea essentially.
    global temperature_scale #pretty much every object in on_frame_configure will have to become a global variable if they are to be passed to the button_frame and then to the endpoint_connector. in short I will have to adapt settings_frame to the object oriented programming model at a minimum. good thing everything I will have to modify is contained within this module.
    global topPSampling
    global presence_penalty_scale
    global frequency_penalty_scale
    global selected_option
    global endpoint
    global apiKey
    global user_name
    #the above global variables will need to be added to a data handler class called SettingsDataHandler
    
    # Create a Canvas widget
    settings_canvas = tk.Canvas(window, width=widthIn, height=heightIn, bg='#E7EAEA')
    settings_canvas.pack(side='left', fill='both', expand=True)

    # Create a Frame widget as a container for all other widgets
    settings_frame = tk.Frame(settings_canvas, bg='#E7EAEA')

    # Create and configure the Scrollbar
    scrollbar = tk.Scrollbar(window, command=settings_canvas.yview)
    scrollbar.pack(side='right', fill='y')

    # Link the Scrollbar to the Canvas
    settings_canvas.configure(yscrollcommand=scrollbar.set)
    
    # Create a window inside the canvas to hold the settings_frame
    settings_canvas.create_window((0, 0), window=settings_frame, anchor='nw')

    # Update the scroll region when the size of the settings_frame changes
    def on_frame_configure(event):
        settings_canvas.configure(scrollregion=settings_canvas.bbox('all'))

    settings_frame.bind('<Configure>', on_frame_configure)
    
    #this widget will set whether to use display settings for an openAI endpoint, google gemini endpoint, or a custom endpoint. this will principally effect whether to display the endpoint widget or as a text entry or two different drop down menus that will allow users to select one of a number of models.
    tk.Label(settings_frame, text="API mode").pack()
    options = ["OpenAI", "Gemini", "OpenAI compatible Endpoint"]
    selected_option = tk.StringVar(settings_frame)
    selected_option.set(options[0])
    option_menu = tk.OptionMenu(settings_frame, selected_option, *options)
    option_menu.pack()
    
    # Add widgets to settings_frame
    #wrap endpoint widget in an if else statement that corespond to the three options of the options widget. if openAI or Gemini are selected, this will display another drop down menu like the selected option widget which will have the names of models that openAI or gemini offer.
    tk.Label(settings_frame, text="Endpoint to connect to").pack()
    endpoint = tk.Entry(settings_frame, bg='#89BCEA')
    endpoint.pack()
    
    #apiKey widget will only appear if selected option is coresponds with openAI or gemini.
    tk.Label(settings_frame, text="API key for OpenAI, Gemini, or similar").pack()
    apiKey = tk.Entry(settings_frame, bg='#89BCEA')
    apiKey.pack()

    tk.Label(settings_frame, text="Tokens to Predict").pack()
    tokens_entry = tk.Entry(settings_frame, bg='#89BCEA')
    tokens_entry.insert(0, '256') #256 is meant to be a default value. when the submit_button widget is pressed, I want the current value that is in the tokens_entry widget to be grabbed and used to restrict the maximum amount of tokens to be generated by supplying it to the max_tokens variable of the commented completion = client.chat.completions.create()
    tokens_entry.pack()

    tk.Label(settings_frame, text="Temperature").pack()
    temperature_scale = tk.Scale(settings_frame, from_=0, to=2, resolution=0.01, orient="horizontal")
    temperature_scale.set(1.0) #1.0 is meant to be a default value. when the submit_button widget is pressed, I want the current value that is in the temperature_scale widget to be grabbed much like the tokens_entry widget.
    temperature_scale.pack()

    tk.Label(settings_frame, text="frequency penalty").pack()
    frequency_penalty_scale = tk.Scale(settings_frame, from_=0, to=2, resolution=0.01, orient="horizontal")
    frequency_penalty_scale.set(1.0)
    frequency_penalty_scale.pack()
    
    tk.Label(settings_frame, text="presence penalty").pack()
    presence_penalty_scale = tk.Scale(settings_frame, from_=0, to=2, resolution=0.01, orient="horizontal")
    presence_penalty_scale.set(1.0)
    presence_penalty_scale.pack()

    tk.Label(settings_frame, text="Top-P Sampling").pack()
    topPSampling = tk.Scale(settings_frame, from_=0, to=1, resolution=0.01, orient="horizontal")
    topPSampling.set(0.95)
    topPSampling.pack()

    tk.Label(settings_frame, text="Username").pack()
    user_name = tk.Entry(settings_frame, bg='#89BCEA')
    user_name.pack()


    # Bind the mouse wheel event to the canvas
    def on_mouse_wheel(event):
        if event.delta:
            settings_canvas.yview_scroll(int(-1*(event.delta/120)), "units")
        elif event.num == 4:  # Linux scroll up
            settings_canvas.yview_scroll(-1, "units")
        elif event.num == 5:  # Linux scroll down
            settings_canvas.yview_scroll(1, "units")

    # Bind the mouse wheel event for Windows and macOS
    settings_canvas.bind_all("<MouseWheel>", on_mouse_wheel)
    # Bind the mouse wheel event for Linux
    settings_canvas.bind_all("<Button-4>", on_mouse_wheel)
    settings_canvas.bind_all("<Button-5>", on_mouse_wheel)

def return_max_tokens():
    #this method is intended for getting a user inputted string of text from the tokens_entry text widget
    returned_data = tokens_entry.get()
    return returned_data #settings_frame.py>button_frame.py(submit_text())>fetch_response()>endpoint_connector.py
    
def return_temp():
    returned_data = temperature_scale.get()
    return returned_data

def main(window, widthIn, heightIn):
    create_settings_frame(window, widthIn, heightIn)

if __name__ == "__main__":
    root = tk.Tk()
    widthIn = 210
    heightIn = 500
    main(root, widthIn, heightIn)
    root.mainloop()


'''
import tkinter as tk

def create_settings_frame(window, widthIn, heightIn):
    # Create a Canvas widget
    settings_canvas = tk.Canvas(window, width=widthIn, height=heightIn, bg='#E7EAEA')
    settings_canvas.pack(side='left', fill='both', expand=True)

    # Create a Frame widget as a container for all other widgets
    settings_frame = tk.Frame(settings_canvas, bg='#E7EAEA')

    # Create and configure the Scrollbar
    scrollbar = tk.Scrollbar(window, command=settings_canvas.yview)
    scrollbar.pack(side='right', fill='y')

    # Link the Scrollbar to the Canvas
    settings_canvas.configure(yscrollcommand=scrollbar.set)
    
    #New Task!: have to figure out a way to make it so that scrolling can occur in the settings frame when using the multitouch gestures of a mousepad or the scrollwheel of a mouse when not directly putting the cursor on the scrollbar.
    
    # Create a window inside the canvas to hold the settings_frame
    settings_canvas.create_window((0, 0), window=settings_frame, anchor='nw')

    # Update the scroll region when the size of the settings_frame changes
    def on_frame_configure(event):
        settings_canvas.configure(scrollregion=settings_canvas.bbox('all'))

    settings_frame.bind('<Configure>', on_frame_configure)

    # Add widgets to settings_frame
    tk.Label(settings_frame, text="Endpoint to connect to").pack()
    endpoint = tk.Entry(settings_frame, bg='#89BCEA')
    endpoint.pack()

    tk.Label(settings_frame, text="API key for OpenAI, Gemini, or similar").pack()
    apiKey = tk.Entry(settings_frame, bg='#89BCEA')
    apiKey.pack()

    tk.Label(settings_frame, text="Tokens to Predict").pack()
    tokens_entry = tk.Entry(settings_frame, bg='#89BCEA')
    tokens_entry.insert(0, '256')
    tokens_entry.pack()

    tk.Label(settings_frame, text="Temperature").pack()
    temperature_scale = tk.Scale(settings_frame, from_=0, to=2, resolution=0.01, orient="horizontal")
    temperature_scale.set(1.0)
    temperature_scale.pack()

    tk.Label(settings_frame, text="Repeat Penalty (repPen)").pack()
    repeat_penalty_scale = tk.Scale(settings_frame, from_=0, to=2, resolution=0.01, orient="horizontal")
    repeat_penalty_scale.set(1.0)
    repeat_penalty_scale.pack()

    tk.Label(settings_frame, text="Tokens to be considered before repPen").pack()
    consideredRepPenalty = tk.Entry(settings_frame, bg='#89BCEA')
    consideredRepPenalty.insert(0, '256')
    consideredRepPenalty.pack()

    tk.Label(settings_frame, text="Penalise repetitions of newlines").pack()
    enable_var = tk.IntVar()
    enable_checkbutton = tk.Checkbutton(settings_frame, variable=enable_var)
    enable_checkbutton.pack()

    tk.Label(settings_frame, text="Advanced options").pack()
    tk.Label(settings_frame, text="Top-K Sampling").pack()
    topKSampling = tk.Scale(settings_frame, from_=0, to=100, resolution=1, orient="horizontal")
    topKSampling.set(40)
    topKSampling.pack()

    tk.Label(settings_frame, text="Top-P Sampling").pack()
    topPSampling = tk.Scale(settings_frame, from_=0, to=1, resolution=0.01, orient="horizontal")
    topPSampling.set(0.95)
    topPSampling.pack()

    tk.Label(settings_frame, text="Min-P Sampling").pack()
    minPSampling = tk.Scale(settings_frame, from_=0, to=1, resolution=0.01, orient="horizontal")
    minPSampling.set(0.05)
    minPSampling.pack()

    tk.Label(settings_frame, text="Selection Setting").pack()
    options = ["Option 1", "Option 2", "Option 3"]
    selected_option = tk.StringVar(settings_frame)
    selected_option.set(options[0])
    option_menu = tk.OptionMenu(settings_frame, selected_option, *options)
    option_menu.pack()

def main(window, widthIn, heightIn):
    create_settings_frame(window, widthIn, heightIn)

if __name__ == "__main__":
    root = tk.Tk()
    widthIn = 210
    heightIn = 500
    main(root, widthIn, heightIn)
    root.mainloop()

'''

'''
import tkinter as tk

def create_settings_frame(window, widthIn, heightIn):
    # Create a Canvas widget
    settings_canvas = tk.Canvas(window, width=widthIn, height=heightIn, bg='#E7EAEA')
    settings_canvas.pack(side='left', fill='both', expand=True)
    print(f"settings_frame: step 1: element width: {widthIn}")
    print(f"step 1: element height: {heightIn}")
    
    # Create and configure the Scrollbar
    scrollbar = tk.Scrollbar(settings_canvas, command=settings_canvas.yview) #same as test
    scrollbar.pack(side='right', fill='y') #same as test
    
    # Link the Scrollbar to the Text widget
    settings_canvas.config(yscrollcommand=scrollbar.set)
    
    # Create a Frame widget as a container for all other widgets
    settings_frame = tk.Frame(window, bg='#E7EAEA', width=widthIn, height=heightIn,)
    settings_canvas.create_window((0, 0), window=settings_frame, anchor='nw')
    
    # Update the scroll region when the size of the settings_frame changes
    def on_frame_configure(event):
        settings_canvas.configure(scrollregion=settings_canvas.bbox('all'))

    settings_frame.bind('<Configure>', on_frame_configure)   
    
    #Add a Label and Entry for Endpoint
    tk.Label(settings_frame, text="Endpoint to connect to").pack()
    endpoint = tk.Entry(settings_frame, bg='#89BCEA')
    endpoint.pack()
    
    #Add a label and Entry for API key
    tk.Label(settings_frame, text="API key for OpenAI, Gemini, or similar").pack()
    apiKey = tk.Entry(settings_frame, bg='#89BCEA')
    apiKey.pack()
    
    # Add a Label and Entry for 'tokens to predict'
    tk.Label(settings_frame, text="Tokens to Predict").pack()
    tokens_entry = tk.Entry(settings_frame, bg='#89BCEA')
    tokens_entry.insert(0, '256') #this sets a default value to the number of tokens to generate
    print(f"tokens_entry: {tokens_entry.get()}")
    tokens_entry.pack()
    tokens_entry.bind('<FocusIn>', lambda event: clear_entry(event, tokens_entry, '256', settings_frame))
    print(f"tokens_entry: {tokens_entry.get()}")

    # Add a Label and Scale for 'temperature'
    tk.Label(settings_frame, text="Temperature").pack()
    temperature_scale = tk.Scale(settings_frame, from_=0, to=2, resolution=0.01, orient="horizontal")
    temperature_scale.set(1.0)
    temperature_scale.pack()

    # Add a Label and Scale for 'repeat penalty'
    tk.Label(settings_frame, text="Repeat Penalty (repPen)").pack()
    repeat_penalty_scale = tk.Scale(settings_frame, from_=0, to=2, resolution=0.01, orient="horizontal")
    repeat_penalty_scale.set(1.0)
    repeat_penalty_scale.pack()
    
    #Add a label and scale for 'Num tokens to be considered for repPen'
    tk.Label(settings_frame, text="tokens to be considered before repPen").pack()
    consideredRepPenalty = tk.Entry(settings_frame, bg='#89BCEA')
    consideredRepPenalty.insert(0, '256') #this sets a default value for the number of tokens to be considered for repPen
    consideredRepPenalty.pack()
    print(f"consideredRepPenalty: {consideredRepPenalty.get()}")
    consideredRepPenalty.bind('<FocusIn>', lambda event: clear_entry(event, consideredRepPenalty, '256', settings_frame))
    print(f"consideredRepPenalty: {consideredRepPenalty.get()}")
    
    # Add a Label and Checkbutton for a boolean setting
    tk.Label(settings_frame, text="penalise repetitions of newlines").pack()
    enable_var = tk.IntVar()
    enable_checkbutton = tk.Checkbutton(settings_frame, variable=enable_var)
    enable_checkbutton.pack()
    
    # Adding Advanced options Top-K, Top-P, Min-P
    tk.Label(settings_frame, text="advanced options").pack()
    tk.Label(settings_frame, text="Top-K Sampling").pack()
    topKSampling = tk.Scale(settings_frame, from_=0, to=100, resolution=1, orient="horizontal")
    topKSampling.set(40)
    topKSampling.pack()

    tk.Label(settings_frame, text="Top-P Sampling").pack()
    topPSampling = tk.Scale(settings_frame, from_=0, to=1, resolution=0.01, orient="horizontal")
    topPSampling.set(0.95)
    topPSampling.pack()
    
    tk.Label(settings_frame, text="Min-P Sampling").pack()
    minPSampling = tk.Scale(settings_frame, from_=0, to=1, resolution=0.01, orient="horizontal")
    minPSampling.set(0.05)
    minPSampling.pack()
    
    # Add a Label and OptionMenu for a selection setting
    tk.Label(settings_frame, text="Selection Setting").pack()
    options = ["Option 1", "Option 2", "Option 3"]
    selected_option = tk.StringVar(settings_frame)
    selected_option.set(options[0])  # default value
    option_menu = tk.OptionMenu(settings_frame, selected_option, *options)
    option_menu.pack()

def clear_entry(event, entry, default_text, settings_frame):
    if entry.get() == default_text:
        entry.delete(0, 'end')
        print(f"cleared entry: {entry.get()}")

def main(window, widthIn, heightIn):
    # Create the output frame
    create_settings_frame(window, widthIn, heightIn)

if __name__ == "__main__":
    main()
'''